# Generated by Django 4.2.7 on 2023-12-02 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectFirst_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='birthDate',
            field=models.DateField(blank=True, default='0000-00-00', null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
