# Generated by Django 4.2.7 on 2023-12-02 12:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectFirst_app', '0003_alter_person_accountcreationdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='accountCreationDate',
            field=models.DateTimeField(blank=True, default=datetime.date(2023, 12, 2)),
        ),
        migrations.AlterField(
            model_name='person',
            name='lastUpdate',
            field=models.DateTimeField(blank=True, default=datetime.date(2023, 12, 2)),
        ),
    ]
