# Generated by Django 4.2.7 on 2023-12-02 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectFirst_app', '0004_alter_person_accountcreationdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='birthDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
