# Generated by Django 4.2.7 on 2023-12-02 12:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectFirst_app', '0008_alter_person_accountcreationdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='accountCreationDate',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 12, 2, 12, 10, 49, 115966, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(default='example@notset.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='person',
            name='lastUpdate',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 12, 2, 12, 10, 49, 115966, tzinfo=datetime.timezone.utc)),
        ),
    ]
