# Generated by Django 4.2.7 on 2023-12-02 12:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectFirst_app', '0010_remove_person_accountcreationdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendship',
            name='approvedDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='lastUpdate',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 12, 2, 12, 29, 11, 36236, tzinfo=datetime.timezone.utc)),
        ),
    ]
