# Generated by Django 4.2.7 on 2023-12-02 15:02

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectFirst_app', '0011_alter_friendship_approveddate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=100)),
                ('cDate', models.DateTimeField()),
                ('eDate', models.DateTimeField()),
                ('access', models.CharField(choices=[('ffa', 'Everybody can open capsule and leave comment'), ('my', 'Only for me'), ('ff', 'For me and my friends. Friends can open and leave comment'), ('custom', 'Custom access list')], default='my', max_length=6)),
            ],
        ),
        migrations.AlterField(
            model_name='friendship',
            name='status',
            field=models.CharField(choices=[('aw', 'awaiting confirmation'), ('a', 'approved'), ('r', 'rejected')], default='aw', max_length=6),
        ),
        migrations.AlterField(
            model_name='person',
            name='lastUpdate',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 12, 2, 15, 2, 27, 674604, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='VaultAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permissions', models.CharField(choices=[('see', 'Only can see the preview'), ('open', 'Can open capsule'), ('r&c', 'Can open capsule and comment')], default='os', max_length=6)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vault', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectFirst_app.vault')),
            ],
        ),
        migrations.AddField(
            model_name='vault',
            name='customAccessList',
            field=models.ManyToManyField(through='projectFirst_app.VaultAccess', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentText', models.TextField()),
                ('commentDate', models.DateField()),
                ('mainComment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projectFirst_app.comments')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('subComments', models.ManyToManyField(to='projectFirst_app.comments')),
            ],
        ),
    ]
