# Generated by Django 4.2.7 on 2023-12-02 15:08

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectFirst_app', '0012_vault_alter_friendship_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vault',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='set_owner', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='lastUpdate',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 12, 2, 15, 8, 14, 289044, tzinfo=datetime.timezone.utc)),
        ),
    ]
