# Generated by Django 4.2.7 on 2023-12-02 15:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectFirst_app', '0013_vault_owner_alter_person_lastupdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='mainComment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projectFirst_app.comments'),
        ),
        migrations.AlterField(
            model_name='person',
            name='lastUpdate',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 12, 2, 15, 11, 56, 54461, tzinfo=datetime.timezone.utc)),
        ),
    ]
