# Generated by Django 4.2.7 on 2023-12-02 15:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectFirst_app', '0015_alter_comments_maincomment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vault',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='lastUpdate',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 12, 2, 15, 42, 41, 574785, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=100)),
                ('extension', models.CharField(max_length=20)),
                ('path', models.CharField(max_length=4000)),
                ('vault', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectFirst_app.vault')),
            ],
        ),
    ]
