# Generated by Django 4.2.7 on 2023-12-03 15:27

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectFirst_app', '0017_alter_person_lastupdate_alter_vault_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='lastUpdate',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 12, 3, 15, 27, 22, 88565, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='vaultaccess',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest', to=settings.AUTH_USER_MODEL),
        ),
    ]
