# Generated by Django 4.2.7 on 2023-12-03 16:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectFirst_app', '0022_alter_comments_vault_alter_person_lastupdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='vault',
        ),
        migrations.AlterField(
            model_name='person',
            name='lastUpdate',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 12, 3, 16, 12, 11, 28583, tzinfo=datetime.timezone.utc)),
        ),
    ]
