# Generated by Django 4.2.7 on 2023-12-03 21:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectFirst_app', '0027_alter_comments_commentdate_alter_person_lastupdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='lastUpdate',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 12, 3, 21, 34, 20, 154992, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_login',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 12, 3, 21, 34, 20, 154992, tzinfo=datetime.timezone.utc)),
        ),
    ]
