# Generated by Django 4.2.7 on 2024-01-05 11:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectFirst_app', '0035_alter_file_path_alter_person_lastupdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='commentDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 1, 5, 11, 41, 3, 673692, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='friendship',
            name='sendDate',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 1, 5, 11, 41, 3, 672695, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='person',
            name='lastUpdate',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 1, 5, 11, 41, 3, 670703, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_login',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 1, 5, 11, 41, 3, 670703, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='vault',
            name='cDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 1, 5, 11, 41, 3, 672695, tzinfo=datetime.timezone.utc)),
        ),
    ]
