# Generated by Django 4.2.7 on 2024-01-06 16:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectFirst_app', '0036_alter_comments_commentdate_alter_friendship_senddate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='commentDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 1, 6, 16, 6, 11, 741072, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='friendship',
            name='sendDate',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 1, 6, 16, 6, 11, 740075, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='person',
            name='lastUpdate',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 1, 6, 16, 6, 11, 738082, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_login',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 1, 6, 16, 6, 11, 738082, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='vault',
            name='cDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 1, 6, 16, 6, 11, 740075, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='vault',
            name='text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
